version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ChimeRoot@9999
      MYSQL_DATABASE: fanlink
      MYSQL_USER: fanlink_user
      MYSQL_PASSWORD: Chime@1989
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL database data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pChimeRoot@9999"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  django:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy  # MySQL must be healthy before Django starts
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=fanlink
      - DATABASE_USER=fanlink_user
      - DATABASE_PASSWORD=Chime@1989
      - SECRET_KEY='django-insecure-=b#f#l0$6b-5@%!q@37z04l0v9gk&91%&529s!e5+9=z8e=dd^'
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media  # Persist uploaded media files
    command: ["sh", "-c", "sleep 10 && python manage.py runserver 0.0.0.0:8000"]
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:  # Named volume for MySQL persistence
  media:  # Persist media files (optional, but not necessary here since it's mapped to a local directory)
