# Generated by Django 5.1.2 on 2024-11-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FanLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArtistName', models.CharField(blank=True, max_length=255, null=True)),
                ('TrackName', models.CharField(blank=True, max_length=255, null=True)),
                ('SpotifyLink', models.CharField(blank=True, max_length=255, null=True)),
                ('AppleLink', models.CharField(blank=True, max_length=255, null=True)),
                ('AmazonLink', models.CharField(blank=True, max_length=255, null=True)),
                ('YoutubeLink', models.CharField(blank=True, max_length=255, null=True)),
                ('ItunesLink', models.CharField(blank=True, max_length=255, null=True)),
                ('AudiomackLink', models.CharField(blank=True, max_length=255, null=True)),
                ('DeezerLink', models.CharField(blank=True, max_length=255, null=True)),
                ('TidalLink', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MediaFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arranger', models.CharField(blank=True, max_length=255, null=True)),
                ('Artist', models.CharField(blank=True, max_length=255, null=True)),
                ('ArtistURL', models.CharField(blank=True, max_length=255, null=True)),
                ('BPM', models.CharField(blank=True, max_length=255, null=True)),
                ('C_Line', models.CharField(blank=True, max_length=255, null=True)),
                ('Keyz', models.CharField(blank=True, max_length=255, null=True)),
                ('Mood', models.CharField(blank=True, max_length=255, null=True)),
                ('DataType', models.CharField(blank=True, max_length=255, null=True)),
                ('Deleted', models.CharField(blank=True, max_length=255, null=True)),
                ('DisplayUPC', models.CharField(blank=True, max_length=255, null=True)),
                ('Download', models.CharField(blank=True, max_length=255, null=True)),
                ('Error', models.CharField(blank=True, max_length=255, null=True)),
                ('Exclusive', models.CharField(blank=True, max_length=255, null=True)),
                ('Genre', models.CharField(blank=True, max_length=255, null=True)),
                ('GenreAlt', models.CharField(blank=True, max_length=255, null=True)),
                ('GenreSub', models.CharField(blank=True, max_length=255, null=True)),
                ('GenreSubAlt', models.CharField(blank=True, max_length=255, null=True)),
                ('HiddenTrack', models.CharField(blank=True, max_length=255, null=True)),
                ('ISRC', models.CharField(blank=True, max_length=255, null=True)),
                ('ItunesLink', models.CharField(blank=True, max_length=255, null=True)),
                ('LabelCatalogNo', models.CharField(blank=True, max_length=255, null=True)),
                ('LabelName', models.CharField(blank=True, max_length=255, null=True)),
                ('Language', models.CharField(blank=True, max_length=255, null=True)),
                ('ManufacturerUPC', models.CharField(blank=True, max_length=255, null=True)),
                ('MasterCarveouts', models.TextField(blank=True, null=True)),
                ('P_Line', models.CharField(blank=True, max_length=255, null=True)),
                ('ParentalAdvisory', models.CharField(blank=True, max_length=255, null=True)),
                ('PreviewClipDuration', models.CharField(blank=True, max_length=255, null=True)),
                ('PreviewClipStartTime', models.CharField(blank=True, max_length=255, null=True)),
                ('PriceBand', models.CharField(blank=True, max_length=255, null=True)),
                ('Producer', models.CharField(blank=True, max_length=255, null=True)),
                ('Publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('RecordingArtist', models.CharField(blank=True, max_length=255, null=True)),
                ('ReleaseDate', models.CharField(blank=True, max_length=255, null=True)),
                ('ReleaseName', models.CharField(blank=True, max_length=255, null=True)),
                ('RoyaltyRate', models.CharField(blank=True, max_length=255, null=True)),
                ('SalesEndDate', models.CharField(blank=True, max_length=255, null=True)),
                ('SalesStartDate', models.CharField(blank=True, max_length=255, null=True)),
                ('SongVersion', models.CharField(blank=True, max_length=255, null=True)),
                ('Territories', models.TextField(blank=True, null=True)),
                ('TerritoriesCarveouts', models.TextField(blank=True, null=True)),
                ('Title', models.CharField(blank=True, max_length=255, null=True)),
                ('TotalTracks', models.CharField(blank=True, max_length=255, null=True)),
                ('TotalVolumes', models.CharField(blank=True, max_length=255, null=True)),
                ('TrackDuration', models.CharField(blank=True, max_length=255, null=True)),
                ('TrackNo', models.CharField(blank=True, max_length=255, null=True)),
                ('VendorName', models.CharField(blank=True, max_length=255, null=True)),
                ('VolumeNo', models.CharField(blank=True, max_length=255, null=True)),
                ('WholesalePrice', models.CharField(blank=True, max_length=255, null=True)),
                ('Writer', models.CharField(blank=True, max_length=255, null=True)),
                ('zIDKey_UPCISRC', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
