# Generated by Django 5.1.2 on 2024-12-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createFanlink', '0003_releases'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanlinks',
            name='Description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fanlinks',
            name='ReleaseDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fanlinks',
            name='UPC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
