# Generated by Django 5.1.2 on 2024-12-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createFanlink', '0004_fanlinks_description_fanlinks_releasedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanlinks',
            name='Source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
